<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tr10"
    nsURI="http://tr10" nsPrefix="tr10">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eAnnotations source="Prop">
      <details key="elements" value=""/>
      <details key="cardinality" value="2..8"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eAnnotations source="Prop">
      <details key="elements" value=""/>
      <details key="cardinality" value="2..8"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
